# ---------------- #
#   Main Configs   #
# ---------------- #
baseurl:
url: https://yunwan1x.github.io
date_format: "ordinal"
title: 彩虹糖
subtitle: "三省吾身，始于言，立于行"
description: "汪云的个人博客"
keywords:  汪云, yunwan1x, 程序员
timezone: Asia/Shanghai
encoding: "utf-8"
side_bar_repo_limit: 5
repository: yunwan1x/yunwan1x.github.io
copyright:
    enabled: false
# 对 css 和 js 资源的 cdn 加速配置
cdn:
    jsdelivr:
        enabled: false
# 可选组件配置
components:
    # 分享
    # weibo,qq,wechat,douban,qzone,linkedin,facebook,twitter
    share:
        enabled: false
        hide-platforms: qq,facebook,linkedin,twitter
    # 不蒜子访问统计
    busuanzi:
        enabled: false
        start_date: 2021-07-28
    # My Popular Repositories
    side_bar_repo:
        enabled: false
        limit: 5
    # 文章字数统计
    word_count:
        enabled: false
    # 页面右上角，以及「关于」页面的二维码
    # 修改图片请替换 assets/images/qrcode.jpg
    qrcode:
        enabled: false
        image_alt: 闷骚的程序员
# 压缩页面内容
compress_html:
  clippings: all
  comments: ["<!--", "-->"]
# 代码高亮风格，支持的 theme 列表见 https://github.com/mzlogin/rouge-themes
highlight_theme: github

# ---------------- #
#      Author      #
# ---------------- #
author: Yun Wang
organization:
organization_url:
github_username: yunwan1x
location: BeiJing, China
email: vs2010wy@live.cn

# ---------------- #
#    Navigation    #
# ---------------- #
navs:
  -
    href: /
    label: 首页
#   -
#     href: /wiki/
#     label: 维基
  -
    href: /my-document/
    label: 书签

  -
    href: /playground/
    label: 游乐场
  -
    href: /awesome-cn/
    label: 开源



  #-
   # href: /links/
    #label: 链接

  #-
    #href: /about/
   # label: 关于

# ---------------- #
#       RSS        #
# ---------------- #
subscribe_rss: /feed.xml

# ---------------- #
#      Jekyll      #
# ---------------- #
markdown: kramdown
kramdown:
    input: GFM
highlighter: rouge
paginate: 10
lsi: false
quiet: false
excerpt_separator: "\n"
permalink: /:year/:month/:day/:title/
plugins:
    - jekyll-github-metadata
    - rouge
#     - jekyll-html-pipeline
    - jekyll-paginate
    - jekyll-sitemap
    - jekyll-feed
    - jemoji
#     - jekyll-mentions
collections:
    wiki:
        output: true
        permalink: /wiki/:path/

# ---------------- #
#      Comments    #
# ---------------- #
# support provider: disqus, gitment, gitalk

#comments_provider: gitalk

# https://github.com/gitalk/gitalk#install
gitalk:
    owner: yunwan1x
    repo: yunwan1x.github.io
    clientID: 762b2d245adbd42c27a5
    clientSecret: f6fa4d544e092ac6fac95bf9bcd0a78ab9f1eb5b
    # admin类似于a,b,c
    admin: yunwan1x
# 在使用其它评论组件时可点击显示 Disqus
lazy_load_disqus : false

# ---------------- #
#      Search      #
# ---------------- #
simple_jekyll_search:
    # 是否支持全文搜索
    fulltext: true
    # 最多显示多少条搜索结果
    limit: 20


